language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
before_install:
  - "pip install -U pip"
  - "python setup.py install"
install:
  - pip install unittest2
  - pip install adafruit_pca9685
  - pip install smars-library
script: python test/test_suite.py
